Import('qt_env')

env = qt_env.Clone()

env.AppendUnique(CPPDEFINES = [ 'CHECKFNIS_LIBRARY' ])

# Le sigh. SOmething v. odd in QT4
env['CPPPATH'] += [
    '.',
]

lib = env.SharedLibrary('checkFNIS', env.Glob('*.cpp'))
env.InstallModule(lib)

res = env['QT_USED_MODULES']
Return('res')
